trigger:
  branches:
    include:
      - develop

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      echo Instalowanie zależności...
      npm install
    displayName: 'Install dependencies'

  - script: |
      echo Budowanie aplikacji...
      npm run build
    displayName: 'Build'

  - script: |
      echo Sprawdzanie obecności pliku dist.zip...
      if [ -f "dist.zip" ]; then
        echo Plik dist.zip istnieje.
      else
        echo Plik dist.zip nie istnieje, sprawdź proces budowania.
        exit 1
      fi
    displayName: 'Check if dist.zip exists'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'dist.zip'
      publishLocation: 'Container'
