trigger:
  branches:
    include:
      - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: '1c9b1cea-b27a-4a48-80ed-545acc9d1ea5'
  functionName: 'workon-backend'
  environmentName: 'production'

steps:
  - script: npm install
    displayName: 'Install dependencies'

  - script: npm start
    displayName: 'Start application'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'workon-backend-artifact'
      publishLocation: 'container'

  - script: ls -la $(Build.ArtifactStagingDirectory)
    displayName: 'List artifact staging directory'
