trigger:
  branches:
    include:
      - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: '3e185b0a-58eb-4c04-bfd1-32d364e42d5b'
  functionName: 'workon-backend'
  environmentName: 'production'

steps:
  - script: npm install
    displayName: 'Install dependencies'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(functionName).zip'
      replaceExistingArchive: true
    displayName: 'Create zip package'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(functionName).zip'
      ArtifactName: 'workon-backend-artifact'
      publishLocation: 'container'
    displayName: 'Publish Artifact'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: '$(azureSubscription)'
      appName: '$(functionName)'
      appType: 'node'
      package: '$(Build.ArtifactStagingDirectory)/$(functionName).zip'
      environmentName: '$(environmentName)'
    displayName: 'Deploy to Azure Web App'
