trigger:
  branches:
    include:
      - develop

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      echo Instalowanie zależności...
      npm install
    displayName: 'Install dependencies'

  - script: |
      echo Budowanie aplikacji...
      npm run build
    displayName: 'Build'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'myArtifact'
      publishLocation: 'container'
