trigger:
  branches:
    include:
      - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  appName: 'workon-backend'
  subscriptionName: 'WorkOn'
  resourceGroupName: 'workon-resource-group'
  location: 'West Europe'

steps:
  - script: |
      echo Instalowanie zależności...
      npm install
    displayName: 'Install dependencies'

  - script: |
      echo Instalowanie zip...
      sudo apt-get install zip
    displayName: 'Install zip'

  - script: |
      echo Budowanie aplikacji...
      npm run build
    displayName: 'Build'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)/dist'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/dist.zip'
      replaceExistingArchive: true
    displayName: 'Archive files'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/dist.zip'
      ArtifactName: 'drop'
      publishLocation: 'Container'
    displayName: 'Publish Artifact'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: '$(subscriptionName)'
      appName: '$(appName)'
      appType: 'webAppLinux'
      runtimeStack: 'NODE|14-lts'
      package: '$(Build.ArtifactStagingDirectory)/dist.zip'
    displayName: 'Deploy to Azure App Service'
